import { json, err, nanoid, corsHeaders } from "../lib/utils.js";
import { shouldIndex, indexDocument } from "../lib/ai.js";

export async function attachmentsHandler(request, env, ctx, url, path, method, userId, origin) {
  if(path==="/api/attachments"&&method==="GET"){const{results}=await env.DB.prepare("SELECT * FROM attachments WHERE user_id=? ORDER BY created_at DESC").bind(userId).all();return json({attachments:results},200,origin);}
  if(path==="/api/attachments"&&method==="POST"){const contentType=request.headers.get("Content-Type")||"";let note_id,filename,mimeType,binary,b64content;if(contentType.includes("application/json")){const body=await request.json();({note_id,filename,type:mimeType,content:b64content}=body);if(!note_id||!filename||!b64content)return err("Missing fields",400,origin);const bs=atob(b64content);binary=new Uint8Array(bs.length);for(let i=0;i<bs.length;i++)binary[i]=bs.charCodeAt(i);}else{note_id=url.searchParams.get("note_id");filename=url.searchParams.get("filename");mimeType=contentType.split(";")[0].trim()||"application/octet-stream";if(!note_id||!filename)return err("Missing params",400,origin);binary=new Uint8Array(await request.arrayBuffer());}const note=await env.DB.prepare("SELECT id FROM notes WHERE id=? AND user_id=?").bind(note_id,userId).first();if(!note)return err("Note not found",404,origin);const attId=nanoid("a_");const r2Key=`${userId}/${note_id}/${attId}/${filename}`;await env.ATTACHMENTS.put(r2Key,binary,{httpMetadata:{contentType:mimeType},customMetadata:{filename,userId,noteId:note_id}});await env.DB.prepare("INSERT INTO attachments (id,note_id,user_id,filename,mime_type,size_bytes,r2_key) VALUES (?,?,?,?,?,?,?)").bind(attId,note_id,userId,filename,mimeType,binary.length,r2Key).run();const skipIndex=url.searchParams.get("skip_index")==="1";const willIndex=!skipIndex&&!!(env.ANTHROPIC_KEY&&shouldIndex(mimeType,filename));if(willIndex){if(!b64content){const C=8192;let s="";for(let i=0;i<binary.length;i+=C)s+=String.fromCharCode(...binary.subarray(i,i+C));b64content=btoa(s);}ctx.waitUntil(indexDocument(env,attId,filename,mimeType,b64content).catch(e=>console.error("Index error:",e.message)));}const attachment=await env.DB.prepare("SELECT * FROM attachments WHERE id=?").bind(attId).first();return json({attachment,indexing:willIndex,indexed:false},201,origin);}
  const attIndexMatch=path.match(/^\/api\/attachments\/([^/]+)\/index$/);if(attIndexMatch&&method==="GET"){const attId=attIndexMatch[1];const att=await env.DB.prepare("SELECT id FROM attachments WHERE id=? AND user_id=?").bind(attId,userId).first();if(!att)return err("Not found",404,origin);const row=await env.DB.prepare("SELECT text_content FROM document_index WHERE attachment_id=?").bind(attId).first();const attRow=await env.DB.prepare("SELECT filename,mime_type FROM attachments WHERE id=?").bind(attId).first();return json({text:row?.text_content||null,indexable:attRow?shouldIndex(attRow.mime_type,attRow.filename):false,pending:attRow?shouldIndex(attRow.mime_type,attRow.filename)&&!row:false},200,origin);}
  const attMatch=path.match(/^\/api\/attachments\/([^/]+)$/);if(attMatch){const attId=attMatch[1];if(method==="GET"){const att=await env.DB.prepare("SELECT * FROM attachments WHERE id=? AND user_id=?").bind(attId,userId).first();if(!att)return err("Not found",404,origin);const obj=await env.ATTACHMENTS.get(att.r2_key);if(!obj)return err("File not found",404,origin);return new Response(obj.body,{headers:{"Content-Type":att.mime_type,"Content-Disposition":`inline; filename="${att.filename}"`,"Cache-Control":"private, max-age=3600",...corsHeaders(origin)}});}if(method==="DELETE"){const att=await env.DB.prepare("SELECT * FROM attachments WHERE id=? AND user_id=?").bind(attId,userId).first();if(!att)return err("Not found",404,origin);await env.ATTACHMENTS.delete(att.r2_key);await env.DB.prepare("DELETE FROM attachments WHERE id=?").bind(attId).run();return json({deleted:true},200,origin);}}
  if(path==="/api/admin/reindex"&&method==="POST"){const{results:u}=await env.DB.prepare("SELECT a.id,a.filename,a.mime_type,a.r2_key FROM attachments a WHERE a.user_id=? AND a.id NOT IN (SELECT attachment_id FROM document_index)").bind(userId).all();const toIndex=u.filter(a=>shouldIndex(a.mime_type,a.filename));if(!toIndex.length)return json({done:true,remaining:0},200,origin);const att=toIndex[0];let status="ok";try{const obj=await env.ATTACHMENTS.get(att.r2_key);if(!obj){status="r2_miss";}else{const buf=await obj.arrayBuffer();const bytes=new Uint8Array(buf);let bin="";for(let i=0;i<bytes.length;i+=32768)bin+=String.fromCharCode(...bytes.subarray(i,Math.min(i+32768,bytes.length)));await indexDocument(env,att.id,att.filename,att.mime_type,btoa(bin));}}catch(e){status="error";console.error("reindex",att.filename,e.message);}await env.DB.prepare("INSERT OR IGNORE INTO document_index (attachment_id,text_content,indexed_at) VALUES (?,?,?)").bind(att.id,"",Math.floor(Date.now()/1e3)).run();return json({done:false,remaining:toIndex.length-1,indexed:{id:att.id,filename:att.filename,status}},200,origin);}

  return null;
}
