import { json, err, nanoid } from "../lib/utils.js";
import { callTrackerAI } from "../lib/ai.js";

export async function trackerHandler(request, env, ctx, url, path, method, userId, origin) {
  if(path==="/api/trackers"&&method==="GET"){const{results}=await env.DB.prepare("SELECT id,name,instructions,ai_model,color,archived,created_at,updated_at FROM tracker_subjects WHERE user_id=? ORDER BY created_at ASC").bind(userId).all();return json({trackers:results},200,origin);}
  if(path==="/api/trackers"&&method==="POST"){const body=await request.json();const{name,instructions="",ai_model="claude",color=null}=body;if(!name?.trim())return err("Name required",400,origin);const id=nanoid("tr_");const now=Math.floor(Date.now()/1e3);await env.DB.prepare("INSERT INTO tracker_subjects (id,user_id,name,instructions,ai_model,color,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,userId,name.trim(),instructions,ai_model,color,now,now).run();const tracker=await env.DB.prepare("SELECT * FROM tracker_subjects WHERE id=?").bind(id).first();return json({tracker},201,origin);}
  const trackerMatch=path.match(/^\/api\/trackers\/([^/]+)$/);
  if(trackerMatch){const tid=trackerMatch[1];const tracker=await env.DB.prepare("SELECT * FROM tracker_subjects WHERE id=? AND user_id=?").bind(tid,userId).first();if(!tracker)return err("Not found",404,origin);if(method==="GET")return json({tracker},200,origin);if(method==="PATCH"){const body=await request.json();const name=body.name!==void 0?body.name.trim():tracker.name;const instructions=body.instructions!==void 0?body.instructions:tracker.instructions;const ai_model=body.ai_model!==void 0?body.ai_model:tracker.ai_model;const color=body.color!==void 0?body.color:tracker.color;const archived=body.archived!==void 0?(body.archived?1:0):(tracker.archived||0);await env.DB.prepare("UPDATE tracker_subjects SET name=?,instructions=?,ai_model=?,color=?,archived=?,updated_at=? WHERE id=?").bind(name,instructions,ai_model,color,archived,Math.floor(Date.now()/1e3),tid).run();const updated=await env.DB.prepare("SELECT * FROM tracker_subjects WHERE id=?").bind(tid).first();return json({tracker:updated},200,origin);}if(method==="DELETE"){await env.DB.prepare("DELETE FROM tracker_subjects WHERE id=?").bind(tid).run();return json({deleted:true},200,origin);}}
  const trackerExportMatch=path.match(/^\/api\/trackers\/([^/]+)\/export$/);
  if(trackerExportMatch&&method==="GET"){const tid=trackerExportMatch[1];const tracker=await env.DB.prepare("SELECT * FROM tracker_subjects WHERE id=? AND user_id=?").bind(tid,userId).first();if(!tracker)return err("Not found",404,origin);const{results:notes}=await env.DB.prepare("SELECT id,content,created_at FROM tracker_notes WHERE tracker_id=? AND user_id=? ORDER BY created_at ASC").bind(tid,userId).all();const{results:conversation}=await env.DB.prepare("SELECT role,content,created_at FROM tracker_conversations WHERE tracker_id=? AND content NOT LIKE '[Auto]%' ORDER BY created_at ASC").bind(tid).all();return json({tracker,notes,conversation},200,origin);}
  const trackerNotesMatch=path.match(/^\/api\/trackers\/([^/]+)\/notes$/);
  if(trackerNotesMatch){const tid=trackerNotesMatch[1];const tracker=await env.DB.prepare("SELECT id FROM tracker_subjects WHERE id=? AND user_id=?").bind(tid,userId).first();if(!tracker)return err("Not found",404,origin);if(method==="GET"){const ps=Math.min(parseInt(url.searchParams.get("pageSize")||"30"),100);const cursor=url.searchParams.get("cursor");let where="tracker_id=? AND user_id=?";const p=[tid,userId];if(cursor){where+=" AND created_at<?";p.push(parseInt(cursor));}p.push(ps+1);const{results:notes}=await env.DB.prepare(`SELECT * FROM tracker_notes WHERE ${where} ORDER BY created_at DESC LIMIT ?`).bind(...p).all();const hasMore=notes.length>ps;if(hasMore)notes.pop();return json({notes,nextCursor:hasMore?notes[notes.length-1].created_at:null},200,origin);}if(method==="POST"){const body=await request.json();const{content=""}=body;if(!content.trim())return err("Content required",400,origin);const id=nanoid("tn_");const now=Math.floor(Date.now()/1e3);await env.DB.prepare("INSERT INTO tracker_notes (id,tracker_id,user_id,content,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(id,tid,userId,content,now,now).run();const note=await env.DB.prepare("SELECT * FROM tracker_notes WHERE id=?").bind(id).first();const tf=await env.DB.prepare("SELECT * FROM tracker_subjects WHERE id=?").bind(tid).first();if(tf?.instructions&&env.ANTHROPIC_KEY){ctx.waitUntil((async()=>{try{const r=await callTrackerAI(env,tf,userId,`New entry logged: ${content}`,[]);if(r){const t=Math.floor(Date.now()/1e3);await env.DB.batch([env.DB.prepare("INSERT INTO tracker_conversations (id,tracker_id,role,content,created_at) VALUES (?,?,?,?,?)").bind(nanoid("tc_"),tid,"user",`[Auto] New entry: ${content}`,t),env.DB.prepare("INSERT INTO tracker_conversations (id,tracker_id,role,content,created_at) VALUES (?,?,?,?,?)").bind(nanoid("tc_"),tid,"assistant",r,t+1)]);}}catch(e){console.error("Auto AI reply:",e.message);}})());}return json({note},201,origin);}}
  const trackerNoteMatch=path.match(/^\/api\/trackers\/([^/]+)\/notes\/([^/]+)$/);
  if(trackerNoteMatch){const[,tid,nid]=trackerNoteMatch;const tracker=await env.DB.prepare("SELECT id FROM tracker_subjects WHERE id=? AND user_id=?").bind(tid,userId).first();if(!tracker)return err("Not found",404,origin);const note=await env.DB.prepare("SELECT * FROM tracker_notes WHERE id=? AND tracker_id=?").bind(nid,tid).first();if(!note)return err("Not found",404,origin);if(method==="PATCH"){const body=await request.json();const content=body.content!==void 0?body.content:note.content;await env.DB.prepare("UPDATE tracker_notes SET content=?,updated_at=? WHERE id=?").bind(content,Math.floor(Date.now()/1e3),nid).run();return json({note:await env.DB.prepare("SELECT * FROM tracker_notes WHERE id=?").bind(nid).first()},200,origin);}if(method==="DELETE"){await env.DB.prepare("DELETE FROM tracker_notes WHERE id=?").bind(nid).run();return json({deleted:true},200,origin);}}
  const trackerConvMatch=path.match(/^\/api\/trackers\/([^/]+)\/conversation$/);
  if(trackerConvMatch){const tid=trackerConvMatch[1];const tracker=await env.DB.prepare("SELECT * FROM tracker_subjects WHERE id=? AND user_id=?").bind(tid,userId).first();if(!tracker)return err("Not found",404,origin);if(method==="GET"){const{results}=await env.DB.prepare("SELECT id,role,content,created_at FROM tracker_conversations WHERE tracker_id=? ORDER BY created_at ASC").bind(tid).all();return json({conversation:results},200,origin);}if(method==="DELETE"){await env.DB.prepare("DELETE FROM tracker_conversations WHERE tracker_id=?").bind(tid).run();return json({ok:true},200,origin);}}
  const trackerAIMatch=path.match(/^\/api\/trackers\/([^/]+)\/ai$/);
  if(trackerAIMatch&&method==="POST"){const tid=trackerAIMatch[1];const tracker=await env.DB.prepare("SELECT * FROM tracker_subjects WHERE id=? AND user_id=?").bind(tid,userId).first();if(!tracker)return err("Not found",404,origin);const{message}=await request.json();if(!message?.trim())return err("Message required",400,origin);const{results:history}=await env.DB.prepare("SELECT role,content FROM tracker_conversations WHERE tracker_id=? ORDER BY created_at DESC LIMIT 20").bind(tid).all();const reply=await callTrackerAI(env,tracker,userId,message.trim(),history.reverse());const now=Math.floor(Date.now()/1e3);await env.DB.batch([env.DB.prepare("INSERT INTO tracker_conversations (id,tracker_id,role,content,created_at) VALUES (?,?,?,?,?)").bind(nanoid("tc_"),tid,"user",message.trim(),now),env.DB.prepare("INSERT INTO tracker_conversations (id,tracker_id,role,content,created_at) VALUES (?,?,?,?,?)").bind(nanoid("tc_"),tid,"assistant",reply,now+1)]);return json({reply},200,origin);}

  return null;
}
